"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1lqk9sp!c%z-iafriwr-6s%sqo=twqn)#p+m-km%&mippcaq%_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',                  # <--- Jazzmin siempre primero
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',            # <--- Librería para Excel
    'calculos',                 # <--- Tu aplicación
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # <--- Carpeta de plantillas personalizadas
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================================================
# CONFIGURACIÓN DE JAZZMIN (TÍTULOS, ÍCONOS Y ORDEN)
# =========================================================
JAZZMIN_SETTINGS = {
    # Títulos y Textos
    "site_title": "Registro Horas Extras",
    "site_header": "",
    "site_brand": "Dirección de Personal",
    "site_logo": "logo.png",
    "login_logo": "logo.png",
    "welcome_sign": "Bienvenido al Sistema de Registro de Horas Adicionales",
    "copyright": "Municipalidad de Chajarí",
    "search_model": "calculos.Empleado", 

    # --- ÍCONOS DEL MENÚ LATERAL (FontAwesome) ---
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # TUS MODELOS:
        "calculos.Secretaria": "fas fa-landmark",      # Secretaría
        "calculos.Departamento": "fas fa-building",    # Departamento
        "calculos.Periodo": "fas fa-calendar-alt",     # Calendario
        "calculos.Empleado": "fas fa-id-card",         # Tarjeta de ID / Empleado
        "calculos.RegistroHora": "fas fa-clock",       # Reloj
    },
    
    # Orden del menú
    "order_with_respect_to": [
        "calculos.RegistroHora",
        "calculos.Empleado",
        "calculos.Periodo",
        "calculos.Departamento",
        "calculos.Secretaria",
        "auth"
    ],
}

# =========================================================
# PERSONALIZACIÓN DE COLORES (AZUL Y NARANJA)
# =========================================================
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": True,
    "brand_colour": "navbar-navy",        # Fondo del logo: Azul Marino
    "accent": "accent-warning",           # Acentos: Naranja
    "navbar": "navbar-navy",              # Barra superior: Azul Marino
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-warning",    # Menú: Oscuro con selección Naranja
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    
    # Colores de botones personalizados
    "button_classes": {
        "primary": "btn-primary",       
        "secondary": "btn-warning",     # Importar/Exportar (Naranja)
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-primary"        # Agregar (Azul)
    }
}