# Generated by Django 5.2.8 on 2025-11-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre (ej: Período 01)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo? (Período Actual)')),
                ('cerrado', models.BooleanField(default=False, verbose_name='¿Cerrado? (Bloquea ediciones)')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Secretaría')),
            ],
            options={
                'verbose_name': 'Secretaría',
                'verbose_name_plural': 'Secretarías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('legajo', models.CharField(max_length=20, unique=True, verbose_name='Número de Legajo')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculos.departamento', verbose_name='Departamento Habitual')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_horas', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Cantidad de Horas')),
                ('departamento_imputacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculos.departamento', verbose_name='Departamento (Imputación)')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculos.empleado', verbose_name='Empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculos.periodo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Registro de Hora',
                'verbose_name_plural': 'Registros de Horas',
                'ordering': ['periodo', 'empleado'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculos.secretaria', verbose_name='Secretaría'),
        ),
    ]
