# Generated by Django 5.2.8 on 2025-11-30 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('legajo', models.CharField(max_length=20, unique=True, verbose_name='Número de Legajo')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puesto / Cargo')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la actividad')),
                ('cantidad_horas', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Cantidad de Horas')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo / Descripción')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('AP', 'Aprobado'), ('RE', 'Rechazado')], default='PE', max_length=2, verbose_name='Estado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculos.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Registro de Hora',
                'verbose_name_plural': 'Registros de Horas',
                'ordering': ['-fecha'],
            },
        ),
    ]
