# Generated by Django 5.2.8 on 2025-11-30 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='secretaria',
        ),
        migrations.AddField(
            model_name='registrohora',
            name='confirmar_exceso',
            field=models.BooleanField(default=False, help_text='Marque esta casilla si está seguro de cargar más de 180 horas.', verbose_name='Confirmar exceso (>180hs)'),
        ),
        migrations.AlterField(
            model_name='registrohora',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculos.periodo', verbose_name='Período'),
        ),
        migrations.DeleteModel(
            name='Secretaria',
        ),
    ]
