# Generated by Django 5.2.8 on 2025-11-30 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0002_alter_empleado_options_remove_empleado_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre (ej: Período 01)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AlterField(
            model_name='registrohora',
            name='fecha',
            field=models.DateField(verbose_name='Fecha exacta'),
        ),
        migrations.AddField(
            model_name='registrohora',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculos.periodo', verbose_name='Período'),
        ),
    ]
