# Generated by Django 5.2.8 on 2025-11-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0002_remove_departamento_secretaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Secretaría')),
            ],
            options={
                'verbose_name': 'Secretaría',
                'verbose_name_plural': 'Secretarías',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='registrohora',
            name='confirmar_exceso',
        ),
        migrations.AddField(
            model_name='departamento',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculos.secretaria', verbose_name='Secretaría'),
        ),
    ]
