# Generated by Django 5.2.8 on 2025-11-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0003_periodo_alter_registrohora_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='activo',
        ),
        migrations.AddField(
            model_name='periodo',
            name='cerrado',
            field=models.BooleanField(default=False, verbose_name='¿Cerrado? (Bloquea ediciones)'),
        ),
    ]
