# Generated by Django 5.2.8 on 2025-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0003_secretaria_remove_registrohora_confirmar_exceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohora',
            name='confirmar_exceso',
            field=models.BooleanField(default=False, help_text='Marque si carga más de 180hs.', verbose_name='Confirmar >180hs'),
        ),
    ]
