# Generated by Django 5.2.8 on 2025-11-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0004_remove_periodo_activo_periodo_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo? (Período Actual)'),
        ),
    ]
